[WIP #1] Support for NSX client
IBM-tfproviders/govnsx pull request #2
Opened 2017-05-03 15:28 UTC by rachappag

Added very basic support to initialize NSX Clinet

2017-05-04 09:30 UTC, chandidas requested changes

2017-05-04 09:30 UTC, chandidas commented on client.go
> +	*resty.Request
Add explicit variable (say, req) for readability.

2017-05-04 09:30 UTC, chandidas commented on client.go
> +type NsxManagerParams struct {
Change name of the structure to NsxManagerConfig

2017-05-04 09:30 UTC, chandidas commented on client.go
> +	RestAgentName string
Change member RestAgentName to UserAgentName.. for better meaning

2017-05-04 09:30 UTC, chandidas commented on client.go
> +func NewClient(mgrParams *NsxManagerParams) (*Client, error) {
Why mgrParams are not stored locally?

2017-05-04 11:25 UTC, rachappag commented on client.go
> +	*resty.Request
added explicit symbolic ref

2017-05-04 11:25 UTC, rachappag commented on client.go
> +	RestAgentName string
Changed

2017-05-04 11:26 UTC, rachappag commented on client.go
> +func NewClient(mgrParams *NsxManagerParams) (*Client, error) {
ToDo added as comment in the code

2017-05-05 10:35 UTC, chandidas approved these changes

2017-05-05 10:36 UTC, merged